name: gastos
description: Una aplicaciÃ³n para gestionar gastos personales.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5+1
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  open_file: ^3.5.10
  intl: ^0.20.2
  file_picker: ^8.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/images/drawer_background.jpg
    - assets/images/frieren 221.jpg
    - assets/images/frieren.jpg
    - assets/images/isla.jpg
    - assets/images/marin 239.jpg
    - assets/images/mitsuri 34.jpg
    - assets/images/rezero 178.jpg
    - assets/fonts/Roboto-Bold.ttf
    - assets/fonts/Roboto-Regular.ttf
